web:
  build: .
  links:
   - db
  ports:
   - "80:8000"
  volumes:
   - .:/usr/src/client/
  environment:
   NODE_ENV: production
   MONGO_URL: mongodb://db:27017/tic-tac-toe
db:
  image: mongo:latest
  ports:
   - "27017:27017"

