web:
  build: .
  dockerfile: Dockerfile-development
  links:
   - db
  ports:
   - "8000:8000"
  volumes:
   - .:/usr/src/client/
  environment:
   NODE_ENV: development
   MONGO_URL: mongodb://db:27017/tic-tac-toe
db:
  image: mongo:latest
  ports:
   - "27017:27017"

